### PR TITLE
overwrite get_initial_state, otherwise it won't work properly

### PR DESCRIPTION
**Pull request by Kunge**
To my best of knowledge (and the result of my nlp experiment supports the point), LSTM resets its state to be initial state before processing new data, so the "get_initial_state" should be overwriten.

### CODE REVIEW

**Comment by CyberZHG** [comment]
Thanks for the PR. However, I think the default `get_initial_state` is the same as your modification:

https://github.com/tensorflow/tensorflow/blob/d7998bb26af28059b4311be995e8a9b6d42f96f3/tensorflow/python/keras/layers/recurrent.py#L599-L609

**Comment by Kunge** [comment]
Actually they are not same, the main difference is argument "batchsize". Check the implementation of LSTMCell in the same file at line 2290.

**Comment by CyberZHG** [comment]
I'm not able to figure out the difference. I think `batch_size` equals to `array_ops.shape(inputs)[0]` in both cases.

**Comment by Kunge** [comment]
> I'm not able to figure out the difference. I think batch_size equals to array_ops.shape(inputs)[0] in both cases.

What's weird is, the cell seems not be trained without overwriting the get_initial_state like the official LSTMCell. I implemented my own onlstm under old api and find it fails when migrated to keras. Then I try your implementation and meet the similar problem, but all things get resolved when add this (which seems unnecessary). Did you try the cell with some tasks like text classification?

**Comment by Kunge** [comment]
I'm also confused about this, but the official LSTMCell does this. Anyway, just remind this may cause some weird problems (all my experiments under eager mode). 

PS. the official GRUCell also overwrites this function at line 1746, so I think there's sth hidden in keras engine about this. It's appreciated if you know the secret and teach me : ).

**Comment by CyberZHG** [comment]
There is a simple classification task in unit tests. But I haven't used it in eager mode.

**Comment by Kunge** [comment]
I know the reason. Line 588 lies in RNN, the RNN will call its cell's get_intial_state, so all cells (grucell, lstmcell, onlstmcell) must implement get_intial_state. My PR add get_intial_state in onlstmcell not onlstm.

**Pull request closed without merging**
